#!/bin/bash
image="${1}"

holeDir="$(readlink -m $(dirname "${0}"))"
baseDir="$(dirname "$(dirname "${holeDir}")")"

verifyImage="$(${baseDir}/createImage "php-5.5" "${holeDir}/fizzbuzz.php")"

function verify() {
    local num="${1}"

    diff <(${baseDir}/execute -c "NUM=${num}" "${verifyImage}") <(${baseDir}/execute -c "NUM=${num}" "${image}") || exit 1
}

verify 100
verify 1000
for i in $(seq 1 8); do
    verify $[$RANDOM % 900 + 100]
done
